Initial push
WCSC/wcsc.github.io pull request #5
Opened 2018-02-03 21:27 UTC by jbnetcat

No comments really.

2018-02-05 23:04 UTC, SilexOne commented on knowledge/jonathan/Bash-Guide-WCSC/_config.yml
> +theme: jekyll-theme-cayman
Get rid of this file.

2018-02-05 23:05 UTC, SilexOne commented on knowledge/jonathan/Bash-Guide-WCSC/README.md
> +The purpose of this **Bash** guide/tutorial is to assist new and seasoned members of the **WhiteHatters Computer Security Club**. It also serves as a handy online quick-reference for tips, tricks, an
Move the content of this file on top of your bash guide then delete this file.

2018-02-05 23:07 UTC, SilexOne requested changes
I would prefer markdown but HTML is fine. Review the inline code comments.

2018-02-08 22:43 UTC, jbnetcat commented
Made 3 changes

2018-02-26 00:55 UTC, jbnetcat commented
Updates applied.

2018-02-26 00:59 UTC, jbnetcat commented
Changes applied

2018-04-05 21:26 UTC, SilexOne approved these changes
cool story!

2018-04-05 21:29 UTC, merged